{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Activity profile correlation: lambda vs sigma_z"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import argparse\n",
    "import pdb\n",
    "import itertools\n",
    "import sys\n",
    "import os\n",
    "import logging\n",
    "import copy\n",
    "import time\n",
    "import signal\n",
    "import numpy as np\n",
    "import scipy\n",
    "import ray\n",
    "from tqdm import tqdm, trange\n",
    "from apply import apply"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "sys.path.insert(0, '/home/mhg19/Manuscripts/PNAS19/network')\n",
    "from network import Population, RateNetwork\n",
    "from transfer_functions import ErrorFunction\n",
    "from connectivity import SparseConnectivity, LinearSynapse, ThresholdPlasticityRule\n",
    "from sequences import GaussianSequence"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'node_ip_address': '10.122.160.26',\n",
       " 'redis_address': '10.122.160.26:6382',\n",
       " 'object_store_address': '/tmp/ray/session_2020-01-23_19-15-43_013143_957635/sockets/plasma_store',\n",
       " 'raylet_socket_name': '/tmp/ray/session_2020-01-23_19-15-43_013143_957635/sockets/raylet',\n",
       " 'webui_url': 'http://10.122.160.26:8080/?token=45fa8858d23069adcb4476112d91a9cb6134286800bea7f2',\n",
       " 'session_dir': '/tmp/ray/session_2020-01-23_19-15-43_013143_957635'}"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ray.init(redis_address=\"10.122.160.26:6382\", include_webui=True, ignore_reinit_error=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'10.122.160.21', '10.122.160.26', '10.122.160.27', '10.122.160.34', '10.122.160.25', '10.122.160.35'}\n"
     ]
    }
   ],
   "source": [
    "@ray.remote\n",
    "def f():\n",
    "    time.sleep(0.01)\n",
    "    return ray.services.get_node_ip_address()\n",
    "\n",
    "# Get a list of the IP addresses of the nodes that have joined the cluster.\n",
    "print(set(ray.get([f.remote() for _ in range(1000)])))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_simulation(lambda_, sigma_z):\n",
    "    N = 40000\n",
    "    T = 0.4\n",
    "    S, P = 1, 30\n",
    "    n_days = 30 #30\n",
    "    \n",
    "    exc = Population(N, tau=1e-2, phi=ErrorFunction(mu=0.07, sigma=0.05).phi)\n",
    "    \n",
    "    conn = SparseConnectivity(source=exc, target=exc, p=0.005, seed=42, disable_pbar=True)\n",
    "    sequences = [GaussianSequence(P,exc.size,seed=i) for i in range(S)]\n",
    "    patterns = np.stack([s.inputs for s in sequences])\n",
    "    \n",
    "    plasticity = ThresholdPlasticityRule(x_f=1.645, q_f=0.8)\n",
    "    synapse = LinearSynapse(conn.K, A=14)\n",
    "    conn.store_sequences(patterns, synapse.h_EE, plasticity.f, plasticity.g)\n",
    "    \n",
    "    # Weight components\n",
    "    rng = np.random.RandomState(seed=43)\n",
    "    W_sequence = np.copy(conn.W.data)\n",
    "    W_pert = np.zeros_like(W_sequence) \n",
    "    \n",
    "    state = []\n",
    "    overlaps = []\n",
    "    correlations = []\n",
    "    for n in range(0, n_days):\n",
    "        z_n = rng.normal(scale=1, size=conn.W.data.size)\n",
    "        if n == 0:\n",
    "            W_pert = sigma_z*z_n\n",
    "        else:\n",
    "            W_pert = lambda_*W_pert + np.sqrt(1-lambda_**2)*sigma_z*z_n\n",
    "        conn.W.data = W_sequence + W_pert\n",
    "        \n",
    "        net = RateNetwork(\n",
    "            exc,\n",
    "            c_EE=conn,\n",
    "            formulation=1,\n",
    "            disable_pbar=True)\n",
    "        net.clear_state()\n",
    "        net.simulate(\n",
    "            T,\n",
    "            r0=exc.phi(plasticity.f(patterns[0,0,:])))\n",
    "        m = sequences[0].overlaps(\n",
    "            net,\n",
    "            exc,\n",
    "            plasticity=plasticity,\n",
    "            correlation=False,\n",
    "            disable_pbar=True)\n",
    "        rho = sequences[0].overlaps(\n",
    "            net,\n",
    "            exc,\n",
    "            plasticity=plasticity,\n",
    "            correlation=True,\n",
    "            disable_pbar=True)\n",
    "        state.append(net.exc.state.astype(np.float32))\n",
    "        overlaps.append(m.astype(np.float32))\n",
    "        correlations.append(rho.astype(np.float32))\n",
    "        \n",
    "    # State correlation\n",
    "    corr = np.zeros((n_days, N))\n",
    "    corr_rev = np.zeros((n_days, N))\n",
    "    for n in range(n_days):\n",
    "        corr[n,:] = np.asarray([\n",
    "            scipy.stats.pearsonr(\n",
    "                state[0][i],\n",
    "                state[n][i])[0] for i in range(N)])\n",
    "        corr_rev[n,:] = np.asarray([\n",
    "            scipy.stats.pearsonr(\n",
    "                state[-1][i],\n",
    "                state[n][i])[0] for i in range(N)])\n",
    "        \n",
    "    # Overlap similarity\n",
    "    overlap_similarity_score = 1 - np.sum((overlaps[0]-overlaps[-1])**2)/np.sum(overlaps[0]**2)\n",
    "        \n",
    "    return {\n",
    "        'params': {\n",
    "            'lambda': lambda_,\n",
    "            'sigma_z': sigma_z\n",
    "            \n",
    "        },\n",
    "        'state': {\n",
    "            'corr': corr,\n",
    "            'corr_rev': corr_rev,\n",
    "        },\n",
    "        'overlaps': overlaps,\n",
    "        'correlations': correlations,\n",
    "        'overlap_similarity_score': overlap_similarity_score,\n",
    "        'std_W_sequence': np.std(W_sequence),\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Parameter exploration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "lambda_ = [0.95] #np.arange(0.4,1.15,0.15)\n",
    "sigma_z = np.arange(0.01,0.06,0.01)\n",
    "\n",
    "combinations = list(itertools.product(\n",
    "    np.atleast_1d(lambda_),\n",
    "    np.atleast_1d(sigma_z)))\n",
    "\n",
    "parallel = True\n",
    "object_ids = []\n",
    "run_simulation_ray = ray.remote(num_cpus=4)(run_simulation)\n",
    "\n",
    "n = 0\n",
    "for lambda__, sigma_z_ in combinations[:]:\n",
    "    if parallel:\n",
    "        func = run_simulation_ray.remote\n",
    "    else:\n",
    "        func = run_simulation\n",
    "    object_ids.append(func(lambda__, sigma_z_))\n",
    "    n += 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Collect and store results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  0%|          | 0/5 [00:00<?, ?it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=1447520, ip=10.122.160.34)\u001b[0m /home/mhg19/venv/lib64/python3.7/site-packages/scipy/stats/stats.py:3508: PearsonRConstantInputWarning: An input array is constant; the correlation coefficent is not defined.\n",
      "\u001b[2m\u001b[36m(pid=1447520, ip=10.122.160.34)\u001b[0m   warnings.warn(PearsonRConstantInputWarning())\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 5/5 [40:16<00:00, 585.62s/it]   2020-01-24 15:23:00,861\tERROR worker.py:1621 -- listen_error_messages_raylet: Connection closed by server.\n",
      "2020-01-24 15:23:00,862\tERROR import_thread.py:89 -- ImportThread: Connection closed by server.\n",
      "2020-01-24 15:23:00,864\tERROR worker.py:1521 -- print_logs: Connection closed by server.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 98, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m     ray.worker.global_worker.main_loop()\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 954, in main_loop\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m     task = self._get_next_task_from_raylet()\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 937, in _get_next_task_from_raylet\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m     task = self.raylet_client.get_task()\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"python/ray/_raylet.pyx\", line 335, in ray._raylet.RayletClient.get_task\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 105, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m     job_id=None)\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/utils.py\", line 67, in push_error_to_driver\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"python/ray/_raylet.pyx\", line 371, in ray._raylet.RayletClient.push_error\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957692)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 98, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m     ray.worker.global_worker.main_loop()\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 954, in main_loop\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m     task = self._get_next_task_from_raylet()\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 937, in _get_next_task_from_raylet\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m     task = self.raylet_client.get_task()\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"python/ray/_raylet.pyx\", line 335, in ray._raylet.RayletClient.get_task\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 105, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m     job_id=None)\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/utils.py\", line 67, in push_error_to_driver\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"python/ray/_raylet.pyx\", line 371, in ray._raylet.RayletClient.push_error\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957688)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 98, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m     ray.worker.global_worker.main_loop()\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 954, in main_loop\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m     task = self._get_next_task_from_raylet()\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 937, in _get_next_task_from_raylet\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m     task = self.raylet_client.get_task()\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"python/ray/_raylet.pyx\", line 335, in ray._raylet.RayletClient.get_task\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 105, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m     job_id=None)\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/utils.py\", line 67, in push_error_to_driver\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"python/ray/_raylet.pyx\", line 371, in ray._raylet.RayletClient.push_error\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957695)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 98, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m     ray.worker.global_worker.main_loop()\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 954, in main_loop\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m     task = self._get_next_task_from_raylet()\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 937, in _get_next_task_from_raylet\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m     task = self.raylet_client.get_task()\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"python/ray/_raylet.pyx\", line 335, in ray._raylet.RayletClient.get_task\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 105, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m     job_id=None)\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/utils.py\", line 67, in push_error_to_driver\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"python/ray/_raylet.pyx\", line 371, in ray._raylet.RayletClient.push_error\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957694)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 98, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m     ray.worker.global_worker.main_loop()\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 954, in main_loop\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m     task = self._get_next_task_from_raylet()\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 937, in _get_next_task_from_raylet\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m     task = self.raylet_client.get_task()\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"python/ray/_raylet.pyx\", line 335, in ray._raylet.RayletClient.get_task\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 105, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m     job_id=None)\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/utils.py\", line 67, in push_error_to_driver\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"python/ray/_raylet.pyx\", line 371, in ray._raylet.RayletClient.push_error\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957685)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 98, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m     ray.worker.global_worker.main_loop()\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 954, in main_loop\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m     task = self._get_next_task_from_raylet()\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/worker.py\", line 937, in _get_next_task_from_raylet\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m     task = self.raylet_client.get_task()\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"python/ray/_raylet.pyx\", line 335, in ray._raylet.RayletClient.get_task\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Raylet connection closed.\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m During handling of the above exception, another exception occurred:\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/workers/default_worker.py\", line 105, in <module>\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m     job_id=None)\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"/home/mhg19/.local/lib/python3.7/site-packages/ray/utils.py\", line 67, in push_error_to_driver\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m     worker.raylet_client.push_error(job_id, error_type, message, time.time())\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"python/ray/_raylet.pyx\", line 371, in ray._raylet.RayletClient.push_error\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m   File \"python/ray/_raylet.pyx\", line 109, in ray._raylet.check_status\n",
      "\u001b[2m\u001b[36m(pid=957690)\u001b[0m ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.\n"
     ]
    }
   ],
   "source": [
    "directory = \"/home/mhg19/Manuscripts/PNAS19/figures/notebooks/supplement/3/data/\"\n",
    "pbar = tqdm(total=n)\n",
    "while len(object_ids) > 0:\n",
    "    if parallel:\n",
    "        ready_object_ids, _ = ray.wait(object_ids)\n",
    "        id_ = ready_object_ids[0]\n",
    "        data = ray.get(id_)\n",
    "        object_ids.remove(id_)\n",
    "    else:\n",
    "        data = object_ids[0]\n",
    "        object_ids.remove(data)\n",
    "    params = data['params']\n",
    "    lambda_, sigma_z = params['lambda'], params['sigma_z']\n",
    "    filename = \"lambda%.4f_sigmaz%.4f\"%(\n",
    "        lambda_,sigma_z) + \".npy\"\n",
    "    filepath = directory + filename\n",
    "    np.save(open(filepath, 'wb'), data)\n",
    "    pbar.update(1)\n",
    "    time.sleep(1)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
